/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ActionWith } from './actionWith';

/**
 * An action triggered by the ExecutionGraph, such as sending an alert for approval.
 */
export interface Action {
  id: string;
  label: string;
  with: ActionWith;
}
