/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { CompileError } from './compileError';

export type CompileErrorResponseResponse = {
  compileErrors: CompileError[];
};
