/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { CompileResponseResponseOne } from './compileResponseResponseOne';
import type { CompileResponseResponseTwo } from './compileResponseResponseTwo';

/**
 * Successful compilation response
 */
export type CompileResponseResponse = CompileResponseResponseOne | CompileResponseResponseTwo;
