/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ExecutionGraph } from './executionGraph';

export type CompileResponseResponseOne = {
  graph: ExecutionGraph;
};
