/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export type CompileRequestBody = {
  /** The workflow definition in YAML format */
  workflowDefinition: string;
  /** The input schema in JSON schema format */
  inputSchema: string;
};
