/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface CompileError {
  file: string;
  start: number;
  end: number;
  severity: string;
  msg: string;
}
