/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { Node } from './node';

export interface ExecutionGraph {
  nodes: Node[];
  outcome: string;
  actions: string[];
}
