/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * An individual node in an Execution Graph.
 */
export interface Node {
  id: string;
  predecessors: string[];
  complete: boolean;
  activated: boolean;
  label: string;
}
