/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  CompileResponseResponse,
  CompileRequestBody,
  RunRequestBody
} from '.././types'
import { customInstance } from '../../src/utils/custom-instance';


  
  // eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * Compile a workflow into an execution graph without actually executing it.
 * @summary Compile workflow
 */
export const compileWorkflow = (
    compileRequestBody: CompileRequestBody,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<CompileResponseResponse>(
      {url: `/workflow/compile`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: compileRequestBody
    },
      options);
    }
  

/**
 * Run a workflow.
 * @summary Run workflow
 */
export const runWorkflow = (
    runRequestBody: RunRequestBody,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<CompileResponseResponse>(
      {url: `/workflow/run`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: runRequestBody
    },
      options);
    }
  

